sudo: false
cache: bundler
rvm:
  - 2.1
  - 2.2.5
  - 2.3.1
gemfile:
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
install:
  - gem install rubocop -v 0.57.2
  - gem install bundler -v 1.17.3
  - bundle --version
  - bundle install
script:
  - bundle exec rake test
  - rubocop
matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails51.gemfile
