rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
install:
  - gem install bundler
  - bundle --version
  - bundle install
before_script:
  - bundle exec rake appraisal:setup
script:
  - bundle exec rake appraisal test
