sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
gemfile:
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
install:
  - gem install bundler
  - bundle --version
  - bundle install
before_script:
  - bundle exec appraisal update
script:
  - bundle exec appraisal rake test
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails50.gemfile
